/* Auto-generated by scripts/html2jsx.py — page registry for the legacy catch-all routes. */
import type { ComponentType } from "react";
import type { Locale } from "./locales";

import p_about_en from "@/components/legacy/pages/about.en";
import p_about_cn from "@/components/legacy/pages/about.cn";
import p_about_tw from "@/components/legacy/pages/about.tw";
import p_about_jp from "@/components/legacy/pages/about.jp";
import p_address_check_en from "@/components/legacy/pages/address-check.en";
import p_address_check_cn from "@/components/legacy/pages/address-check.cn";
import p_address_check_tw from "@/components/legacy/pages/address-check.tw";
import p_address_check_jp from "@/components/legacy/pages/address-check.jp";
import p_blog_en from "@/components/legacy/pages/blog.en";
import p_blog_cn from "@/components/legacy/pages/blog.cn";
import p_blog_tw from "@/components/legacy/pages/blog.tw";
import p_blog_jp from "@/components/legacy/pages/blog.jp";
import p_blog_hong_kong_stablecoin_license_en from "@/components/legacy/pages/blog-hong-kong-stablecoin-license.en";
import p_blog_hong_kong_stablecoin_license_jp from "@/components/legacy/pages/blog-hong-kong-stablecoin-license.jp";
import p_blog_hong_kong_stablecoin_license_cn from "@/components/legacy/pages/blog-hong-kong-stablecoin-license.cn";
import p_blog_hong_kong_stablecoin_license_tw from "@/components/legacy/pages/blog-hong-kong-stablecoin-license.tw";
import p_blog_mica_stablecoin_compliance_en from "@/components/legacy/pages/blog-mica-stablecoin-compliance.en";
import p_blog_mica_stablecoin_compliance_jp from "@/components/legacy/pages/blog-mica-stablecoin-compliance.jp";
import p_blog_mica_stablecoin_compliance_cn from "@/components/legacy/pages/blog-mica-stablecoin-compliance.cn";
import p_blog_mica_stablecoin_compliance_tw from "@/components/legacy/pages/blog-mica-stablecoin-compliance.tw";
import p_blog_ofac_sanctions_screening_blockchain_en from "@/components/legacy/pages/blog-ofac-sanctions-screening-blockchain.en";
import p_blog_ofac_sanctions_screening_blockchain_jp from "@/components/legacy/pages/blog-ofac-sanctions-screening-blockchain.jp";
import p_blog_ofac_sanctions_screening_blockchain_cn from "@/components/legacy/pages/blog-ofac-sanctions-screening-blockchain.cn";
import p_blog_ofac_sanctions_screening_blockchain_tw from "@/components/legacy/pages/blog-ofac-sanctions-screening-blockchain.tw";
import p_blog_travel_rule_on_chain_en from "@/components/legacy/pages/blog-travel-rule-on-chain.en";
import p_blog_travel_rule_on_chain_jp from "@/components/legacy/pages/blog-travel-rule-on-chain.jp";
import p_blog_travel_rule_on_chain_cn from "@/components/legacy/pages/blog-travel-rule-on-chain.cn";
import p_blog_travel_rule_on_chain_tw from "@/components/legacy/pages/blog-travel-rule-on-chain.tw";
import p_blog_why_on_chain_compliance_en from "@/components/legacy/pages/blog-why-on-chain-compliance.en";
import p_blog_why_on_chain_compliance_cn from "@/components/legacy/pages/blog-why-on-chain-compliance.cn";
import p_blog_why_on_chain_compliance_tw from "@/components/legacy/pages/blog-why-on-chain-compliance.tw";
import p_blog_why_on_chain_compliance_jp from "@/components/legacy/pages/blog-why-on-chain-compliance.jp";
import p_case_studies_en from "@/components/legacy/pages/case-studies.en";
import p_changelog_en from "@/components/legacy/pages/changelog.en";
import p_changelog_cn from "@/components/legacy/pages/changelog.cn";
import p_changelog_tw from "@/components/legacy/pages/changelog.tw";
import p_changelog_jp from "@/components/legacy/pages/changelog.jp";
import p_contact_en from "@/components/legacy/pages/contact.en";
import p_demo_en from "@/components/legacy/pages/demo.en";
import p_demo_cn from "@/components/legacy/pages/demo.cn";
import p_demo_tw from "@/components/legacy/pages/demo.tw";
import p_demo_jp from "@/components/legacy/pages/demo.jp";
import p_docs_en from "@/components/legacy/pages/docs.en";
import p_docs_cn from "@/components/legacy/pages/docs.cn";
import p_docs_tw from "@/components/legacy/pages/docs.tw";
import p_docs_jp from "@/components/legacy/pages/docs.jp";
import p_docs_api_en from "@/components/legacy/pages/docs-api.en";
import p_docs_api_cn from "@/components/legacy/pages/docs-api.cn";
import p_docs_api_tw from "@/components/legacy/pages/docs-api.tw";
import p_docs_api_jp from "@/components/legacy/pages/docs-api.jp";
import p_docs_sdk_en from "@/components/legacy/pages/docs-sdk.en";
import p_docs_sdk_cn from "@/components/legacy/pages/docs-sdk.cn";
import p_docs_sdk_tw from "@/components/legacy/pages/docs-sdk.tw";
import p_docs_sdk_jp from "@/components/legacy/pages/docs-sdk.jp";
import p_pricing_en from "@/components/legacy/pages/pricing.en";
import p_pricing_cn from "@/components/legacy/pages/pricing.cn";
import p_pricing_tw from "@/components/legacy/pages/pricing.tw";
import p_pricing_jp from "@/components/legacy/pages/pricing.jp";
import p_privacy_en from "@/components/legacy/pages/privacy.en";
import p_privacy_cn from "@/components/legacy/pages/privacy.cn";
import p_privacy_tw from "@/components/legacy/pages/privacy.tw";
import p_privacy_jp from "@/components/legacy/pages/privacy.jp";
import p_security_en from "@/components/legacy/pages/security.en";
import p_security_cn from "@/components/legacy/pages/security.cn";
import p_security_tw from "@/components/legacy/pages/security.tw";
import p_security_jp from "@/components/legacy/pages/security.jp";
import p_terms_en from "@/components/legacy/pages/terms.en";
import p_terms_cn from "@/components/legacy/pages/terms.cn";
import p_terms_tw from "@/components/legacy/pages/terms.tw";
import p_terms_jp from "@/components/legacy/pages/terms.jp";
import p_use_cases_rwa_tokenization_en from "@/components/legacy/pages/use-cases-rwa-tokenization.en";
import p_use_cases_rwa_tokenization_cn from "@/components/legacy/pages/use-cases-rwa-tokenization.cn";
import p_use_cases_rwa_tokenization_tw from "@/components/legacy/pages/use-cases-rwa-tokenization.tw";
import p_use_cases_rwa_tokenization_jp from "@/components/legacy/pages/use-cases-rwa-tokenization.jp";
import p_use_cases_smart_wallet_en from "@/components/legacy/pages/use-cases-smart-wallet.en";
import p_use_cases_smart_wallet_cn from "@/components/legacy/pages/use-cases-smart-wallet.cn";
import p_use_cases_smart_wallet_tw from "@/components/legacy/pages/use-cases-smart-wallet.tw";
import p_use_cases_smart_wallet_jp from "@/components/legacy/pages/use-cases-smart-wallet.jp";
import p_use_cases_stablecoin_compliance_en from "@/components/legacy/pages/use-cases-stablecoin-compliance.en";
import p_use_cases_stablecoin_compliance_cn from "@/components/legacy/pages/use-cases-stablecoin-compliance.cn";
import p_use_cases_stablecoin_compliance_tw from "@/components/legacy/pages/use-cases-stablecoin-compliance.tw";
import p_use_cases_stablecoin_compliance_jp from "@/components/legacy/pages/use-cases-stablecoin-compliance.jp";

export type PageMeta = { title: string; description: string };
export type PageDef = {
  available: readonly Locale[];
  wallet: boolean;
  meta: Partial<Record<Locale, PageMeta>>;
};

export const pageDefs: Record<string, PageDef> = {
    "about": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "About — FidesOrigin | Programmable On-Chain Compliance", description: "FidesOrigin is building the infrastructure for programmable on-chain compliance. Meet the team behind the protocol." },
      cn: { title: "关于我们 — FidesOrigin | 可编程的链上合规", description: "FidesOrigin 正在构建可编程链上合规的基础设施。来了解协议背后的团队。" },
      tw: { title: "關於我們 — FidesOrigin | 可編程的鏈上合規", description: "FidesOrigin 正在構建可編程鏈上合規的基礎設施。來了解協議背後的團隊。" },
      jp: { title: "私たちについて — FidesOrigin | プログラマブルなオンチェーン・コンプライアンス", description: "FidesOrigin はプログラマブルなオンチェーン・コンプライアンスのインフラを構築しています。プロトコルを支えるチームをご紹介します。" },
      },
    },
    "address-check": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: true,
      meta: {
      en: { title: "Address Risk Check | FidesOrigin", description: "Check Ethereum address risk in real-time. FidesOrigin scans 20,000+ risk addresses across OFAC, Chainalysis, and more." },
      cn: { title: "地址风险查询 | FidesOrigin", description: "实时查询以太坊地址风险。FidesOrigin扫描超过20,000个风险地址，涵盖OFAC、Chainalysis等来源。" },
      tw: { title: "地址風險查詢 | FidesOrigin", description: "即時查詢以太坊地址風險。FidesOrigin掃描超過20,000個風險地址，涵蓋OFAC、Chainalysis等來源。" },
      jp: { title: "住所リスクチェック | FidesOrigin", description: "イーサリアム住所のリスクをリアルタイムで確認。FidesOriginはOFAC、Chainalysisなど20,000件以上のリスク住所をスキャンします。" },
      },
    },
    "blog": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "FidesOrigin Blog — Insights on On-Chain Compliance", description: "Deep dives into programmable on-chain compliance, risk engines, and the future of DeFi regulation." },
      cn: { title: "FidesOrigin 博客 — 链上合规深度洞察", description: "风险引擎、DeFi 监管与确定性合规架构的深度解析。" },
      tw: { title: "FidesOrigin 博客 — 鏈上合規深度洞察", description: "風險引擎、DeFi 監管與確定性合規架構的深度解析。" },
      jp: { title: "FidesOrigin ブログ — オンチェーンコンプライアンスのインサイト", description: "リスクエンジン、DeFi 規制、決定論的コンプライアンスのアーキテクチャを深掘りします。" },
      },
    },
    "blog/hong-kong-stablecoin-license": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Hong Kong Stablecoin License: Compliance Requirements — FidesOrigin Blog", description: "Guide to Hong Kong's stablecoin issuer licensing regime. HKMA requirements, reserve management, and on-chain compliance for VASPs." },
      cn: { title: "中国香港稳定币牌照：合规要求 — FidesOrigin 博客", description: "中国香港稳定币发行方牌照制度指南。HKMA 要求、储备资产管理，以及面向 VASP 的链上合规。" },
      tw: { title: "中國香港穩定幣牌照：合規要求 — FidesOrigin 博客", description: "中國香港穩定幣發行方牌照制度指南。HKMA 要求、儲備資產管理，以及面向 VASP 的鏈上合規。" },
      jp: { title: "中国香港ステーブルコインライセンス：コンプライアンス要件 — FidesOrigin ブログ", description: "中国香港のステーブルコイン発行者ライセンス制度ガイド。HKMA の要件、準備資産管理、VASP 向けオンチェーンコンプライアンス。" },
      },
    },
    "blog/mica-stablecoin-compliance": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "MiCA Compliance for Stablecoins: A Technical Guide — FidesOrigin Blog", description: "Technical guide to EU MiCA compliance for stablecoin issuers. On-chain reserve attestations, transaction screening, and regulatory reporting requirements." },
      cn: { title: "稳定币的 MiCA 合规：技术指南 — FidesOrigin 博客", description: "面向稳定币发行方的欧盟 MiCA 合规技术指南。链上储备证明、交易筛查与监管报告要求。" },
      tw: { title: "穩定幣的 MiCA 合規：技術指南 — FidesOrigin 博客", description: "面向穩定幣發行方的歐盟 MiCA 合規技術指南。鏈上儲備證明、交易篩查與監管報告要求。" },
      jp: { title: "ステーブルコインの MiCA コンプライアンス：技術ガイド — FidesOrigin ブログ", description: "ステーブルコイン発行者向け EU MiCA コンプライアンスの技術ガイド。オンチェーン準備資産証明、トランザクションスクリーニング、規制報告要件。" },
      },
    },
    "blog/ofac-sanctions-screening-blockchain": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "OFAC Sanctions Screening on Blockchain: Best Practices — FidesOrigin Blog", description: "Best practices for OFAC sanctions screening on blockchain. How to implement SDN list checks at the smart contract level for stablecoins and DeFi protocols." },
      cn: { title: "区块链上的 OFAC 制裁筛查：最佳实践 — FidesOrigin 博客", description: "区块链上 OFAC 制裁筛查的最佳实践。如何为稳定币与 DeFi 协议在智能合约层实现 SDN 名单核查。" },
      tw: { title: "區塊鏈上的 OFAC 制裁篩查：最佳實踐 — FidesOrigin 博客", description: "區塊鏈上 OFAC 制裁篩查的最佳實踐。如何為穩定幣與 DeFi 協議在智能合約層實現 SDN 名單核查。" },
      jp: { title: "ブロックチェーン上の OFAC サンクションスクリーニング：ベストプラクティス — FidesOrigin ブログ", description: "ブロックチェーン上の OFAC サンクションスクリーニングのベストプラクティス。ステーブルコインと DeFi プロトコル向けに、スマートコントラクトレベルでの SDN リストチェック実装を解説。" },
      },
    },
    "blog/travel-rule-on-chain": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "The Travel Rule On-Chain: What FATF Requires from Stablecoin Transfers — FidesOrigin Blog", description: "FATF Travel Rule requirements for stablecoin transfers in 2026, and why on-chain enforcement beats API-centric screening for pre-settlement compliance." },
      cn: { title: "链上旅行规则：FATF 对稳定币转账的要求 — FidesOrigin 博客", description: "2026 年稳定币转账的 FATF 旅行规则要求，以及结算前合规中链上执行为何优于 API 中心化筛查。" },
      tw: { title: "鏈上旅行規則：FATF 對穩定幣轉帳的要求 — FidesOrigin 博客", description: "2026 年穩定幣轉帳的 FATF 旅行規則要求，以及結算前合規中鏈上執行為何優於 API 中心化篩查。" },
      jp: { title: "オンチェーンのトラベルルール：FATF がステーブルコイン送金に求めるもの — FidesOrigin ブログ", description: "2026 年のステーブルコイン送金における FATF トラベルルール要件と、決済前コンプライアンスにおいてオンチェーンエンフォースメントが API セントリックなスクリーニングに勝る理由。" },
      },
    },
    "blog/why-on-chain-compliance": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Why On-Chain: The End of API-Based Compliance — FidesOrigin", description: "API-based compliance is an architectural mistake. The future is on-chain risk enforcement: deterministic, zero-latency, and impossible to bypass." },
      cn: { title: "为何链上：API 合规模式的终结 — FidesOrigin", description: "基于 API 的合规是一种架构层面的错误。未来属于链上风险执行：确定性、零延迟、无法绕过的原生执行。" },
      tw: { title: "為何鏈上：API 合規模式的終結 — FidesOrigin", description: "基於 API 的合規是一種架構層面的錯誤。未來屬於鏈上風險執行：確定性、零延遲、無法繞過的原生執行。" },
      jp: { title: "なぜオンチェーンか：API ベースコンプライアンスの終焉 — FidesOrigin", description: "API ベースのコンプライアンスはアーキテクチャ的な誤りだ。未来はオンチェーンリスクエンフォースメント：決定論的、ゼロレイテンシー、迂回不可能。" },
      },
    },
    "case-studies": {
      available: ["en"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Case Studies — FidesOrigin | On-Chain Compliance in Production", description: "See how leading stablecoin issuers, RWA platforms, and DeFi protocols use FidesOrigin for deterministic on-chain compliance." },
      },
    },
    "changelog": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Changelog — FidesOrigin | Protocol Updates", description: "Track FidesOrigin protocol updates, security audits, and feature releases. From v1.0 to the latest." },
      cn: { title: "更新日志 — FidesOrigin | 协议动态", description: "追踪 FidesOrigin 的协议更新、安全审计与功能发布。从 v1.0 到最新版本。" },
      tw: { title: "更新日誌 — FidesOrigin | 協議動態", description: "追蹤 FidesOrigin 的協議更新、安全審計與功能發布。從 v1.0 到最新版本。" },
      jp: { title: "変更履歴 — FidesOrigin | プロトコル更新", description: "FidesOrigin のプロトコル更新、セキュリティ監査、機能リリースを追跡します。v1.0 から最新まで。" },
      },
    },
    "contact": {
      available: ["en"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Contact — FidesOrigin | Get Started with On-Chain Compliance", description: "Get in touch with the FidesOrigin team. Request a demo, discuss your compliance needs, or explore partnership opportunities." },
      },
    },
    "demo": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Interactive Demo — FidesOrigin | On-Chain Compliance Engine", description: "Try FidesOrigin's on-chain compliance engine live on Sepolia testnet. Screen addresses, check risk scores, and see quarantine in action." },
      cn: { title: "交互式演示 — FidesOrigin | 链上合规引擎", description: "在 Sepolia 测试网上体验 FidesOrigin 链上合规引擎：筛查地址、查询风险评分、观察隔离机制的实际运作。" },
      tw: { title: "互動式演示 — FidesOrigin | 鏈上合規引擎", description: "在 Sepolia 測試網上體驗 FidesOrigin 鏈上合規引擎：篩查地址、查詢風險評分、觀察隔離機制的實際運作。" },
      jp: { title: "インタラクティブデモ — FidesOrigin | オンチェーン・コンプライアンスエンジン", description: "Sepolia テストネットで FidesOrigin のコンプライアンスエンジンを体験：アドレスのスクリーニング、リスクスコアの確認、隔離の動作を確認できます。" },
      },
    },
    "docs": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Documentation — FidesOrigin", description: "FidesOrigin V2.1 documentation. Quick start, core concepts, Guard integration, architecture overview." },
      cn: { title: "文档 — FidesOrigin", description: "FidesOrigin 文档。快速开始、核心概念、架构概览。" },
      tw: { title: "文件 — FidesOrigin", description: "FidesOrigin 文件。快速開始、核心概念、架構概覽。" },
      jp: { title: "ドキュメント — FidesOrigin", description: "FidesOrigin ドキュメント。クイックスタート、核心概念、アーキテクチャ概要。" },
      },
    },
    "docs/api": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "API Reference — FidesOrigin", description: "FidesOrigin V2.1 REST API reference. Endpoints for address risk checks, rules, batch screening, and monitoring." },
      cn: { title: "API 参考 — FidesOrigin", description: "FidesOrigin REST API 参考。地址风险检查、规则管理和风险评估的端点。" },
      tw: { title: "API 參考 — FidesOrigin", description: "FidesOrigin REST API 參考。地址風險檢查、規則管理和風險評估的端點。" },
      jp: { title: "API リファレンス — FidesOrigin", description: "FidesOrigin REST API リファレンス。住所リスクチェック、ルール管理、リスク評価のエンドポイント。" },
      },
    },
    "docs/sdk": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK V2.1. Install, configure, and integrate on-chain compliance with Guard support." },
      cn: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK。安装、配置并集成链上合规。" },
      tw: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK。安裝、配置並集成鏈上合規。" },
      jp: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK。インストール、設定、オンチェーン・コンプライアンスの統合。" },
      },
    },
    "pricing": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Pricing — FidesOrigin | On-Chain Compliance Infrastructure", description: "Transparent pricing for on-chain compliance infrastructure. Start free, scale as you grow. Built for stablecoin issuers, RWA platforms, and DeFi protocols." },
      cn: { title: "定价 — FidesOrigin | 链上合规基础设施", description: "链上合规基础设施的透明定价。免费开始，随业务增长而扩展。为稳定币发行方、RWA平台和DeFi协议打造。" },
      tw: { title: "定價 — FidesOrigin | 鏈上合規基礎設施", description: "鏈上合規基礎設施的透明定價。免費開始，隨業務成長而擴展。為穩定幣發行方、RWA 平台與 DeFi 協議打造。" },
      jp: { title: "料金プラン — FidesOrigin | オンチェーン・コンプライアンス基盤", description: "オンチェーン・コンプライアンス基盤の透明な料金。無料で始め、成長に合わせて拡張。ステーブルコイン発行者、RWA プラットフォーム、DeFi プロトコル向け。" },
      },
    },
    "privacy": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Privacy Policy — FidesOrigin", description: "FidesOrigin privacy policy. How we handle data, cookies, and user information." },
      cn: { title: "隐私政策 — FidesOrigin", description: "FidesOrigin 隐私政策。我们如何处理数据、Cookie 和用户信息。" },
      tw: { title: "隱私政策 — FidesOrigin", description: "FidesOrigin 隱私政策。我們如何處理數據、Cookie 和用戶信息。" },
      jp: { title: "プライバシーポリシー — FidesOrigin", description: "FidesOrigin プライバシーポリシー。データ、Cookie、ユーザー情報の取り扱いについて。" },
      },
    },
    "security": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Security & Audits — FidesOrigin | Triple-Audited On-Chain Compliance", description: "FidesOrigin has completed 3 rounds of comprehensive security audits, covering 300+ findings. View our audit reports and security posture." },
      cn: { title: "安全与审计 — FidesOrigin | 三轮审计的链上合规", description: "FidesOrigin 已完成三轮全面安全审计，覆盖 300+ 项发现。查看我们的审计报告与安全态势。" },
      tw: { title: "安全與審計 — FidesOrigin | 三輪審計的鏈上合規", description: "FidesOrigin 已完成三輪全面安全審計，覆蓋 300+ 項發現。查看我們的審計報告與安全態勢。" },
      jp: { title: "セキュリティと監査 — FidesOrigin | 三度の監査を経たオンチェーン・コンプライアンス", description: "FidesOrigin は 3 ラウンドの包括的なセキュリティ監査を完了し、300 件以上の指摘に対応しました。監査レポートとセキュリティ体制をご覧ください。" },
      },
    },
    "terms": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Terms of Service — FidesOrigin", description: "FidesOrigin terms of service. Rules and conditions for using our platform." },
      cn: { title: "服务条款 — FidesOrigin", description: "FidesOrigin 服务条款。使用我们平台的规则和条件。" },
      tw: { title: "服務條款 — FidesOrigin", description: "FidesOrigin 服務條款。使用我們平台的規則和條件。" },
      jp: { title: "利用規約 — FidesOrigin", description: "FidesOrigin 利用規約。プラットフォームの使用ルールと条件。" },
      },
    },
    "use-cases/rwa-tokenization": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "RWA Tokenization Compliance — FidesOrigin", description: "Compliant RWA tokenization with on-chain securities enforcement. Accredited investor verification, jurisdiction checks, and on-chain KYC for tokenized real world assets." },
      cn: { title: "RWA 代币化合规 — FidesOrigin", description: "以链上证券执法实现合规的 RWA 代币化。合格投资者验证、司法管辖区校验，以及代币化现实资产的链上 KYC。" },
      tw: { title: "RWA 代幣化合規 — FidesOrigin", description: "以鏈上證券執法實現合規的 RWA 代幣化。合格投資者驗證、司法管轄區校驗，以及代幣化現實資產的鏈上 KYC。" },
      jp: { title: "RWA トークン化コンプライアンス — FidesOrigin", description: "オンチェーンの証券規制執行による RWA トークン化。適格投資家の検証、管轄区域チェック、トークン化実資産のオンチェーン KYC。" },
      },
    },
    "use-cases/smart-wallet": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Smart Wallet Compliance — FidesOrigin | Account Abstraction Risk Screening", description: "Embed on-chain risk screening into smart wallets and account abstraction wallets. Screen every userOp before execution with FidesOrigin." },
      cn: { title: "智能钱包合规 — FidesOrigin | 账户抽象风险筛查", description: "把链上风险筛查嵌入智能钱包与账户抽象钱包。用 FidesOrigin 在每一笔 userOp 执行前完成筛查。" },
      tw: { title: "智能錢包合規 — FidesOrigin | 帳戶抽象風險篩查", description: "把鏈上風險篩查嵌入智能錢包與帳戶抽象錢包。用 FidesOrigin 在每一筆 userOp 執行前完成篩查。" },
      jp: { title: "スマートウォレット コンプライアンス — FidesOrigin | アカウント抽象化のリスクスクリーニング", description: "スマートウォレットおよびアカウント抽象化ウォレットにオンチェーンのリスクスクリーニングを組み込む。FidesOrigin で実行前にすべての userOp を検査します。" },
      },
    },
    "use-cases/stablecoin-compliance": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Stablecoin Compliance Solution — FidesOrigin", description: "Build compliant stablecoins with on-chain risk screening. Meet MiCA, Hong Kong, and global regulations with deterministic compliance enforcement." },
      cn: { title: "稳定币合规方案 — FidesOrigin", description: "用链上风险筛查构建合规稳定币。以确定性的合规执行满足 MiCA、香港及全球监管要求。" },
      tw: { title: "穩定幣合規方案 — FidesOrigin", description: "用鏈上風險篩查構建合規穩定幣。以確定性的合規執行滿足 MiCA、香港及全球監管要求。" },
      jp: { title: "ステーブルコイン コンプライアンスソリューション — FidesOrigin", description: "オンチェーンのリスクスクリーニングで準拠型ステーブルコインを構築。決定論的なコンプライアンス執行で MiCA、香港、各国の規制に対応します。" },
      },
    },
};

export const pageContent: Record<string, Partial<Record<Locale, ComponentType>>> = {
    "about": { en: p_about_en, cn: p_about_cn, tw: p_about_tw, jp: p_about_jp },
    "address-check": { en: p_address_check_en, cn: p_address_check_cn, tw: p_address_check_tw, jp: p_address_check_jp },
    "blog": { en: p_blog_en, cn: p_blog_cn, tw: p_blog_tw, jp: p_blog_jp },
    "blog/hong-kong-stablecoin-license": { en: p_blog_hong_kong_stablecoin_license_en, cn: p_blog_hong_kong_stablecoin_license_cn, tw: p_blog_hong_kong_stablecoin_license_tw, jp: p_blog_hong_kong_stablecoin_license_jp },
    "blog/mica-stablecoin-compliance": { en: p_blog_mica_stablecoin_compliance_en, cn: p_blog_mica_stablecoin_compliance_cn, tw: p_blog_mica_stablecoin_compliance_tw, jp: p_blog_mica_stablecoin_compliance_jp },
    "blog/ofac-sanctions-screening-blockchain": { en: p_blog_ofac_sanctions_screening_blockchain_en, cn: p_blog_ofac_sanctions_screening_blockchain_cn, tw: p_blog_ofac_sanctions_screening_blockchain_tw, jp: p_blog_ofac_sanctions_screening_blockchain_jp },
    "blog/travel-rule-on-chain": { en: p_blog_travel_rule_on_chain_en, cn: p_blog_travel_rule_on_chain_cn, tw: p_blog_travel_rule_on_chain_tw, jp: p_blog_travel_rule_on_chain_jp },
    "blog/why-on-chain-compliance": { en: p_blog_why_on_chain_compliance_en, cn: p_blog_why_on_chain_compliance_cn, tw: p_blog_why_on_chain_compliance_tw, jp: p_blog_why_on_chain_compliance_jp },
    "case-studies": { en: p_case_studies_en },
    "changelog": { en: p_changelog_en, cn: p_changelog_cn, tw: p_changelog_tw, jp: p_changelog_jp },
    "contact": { en: p_contact_en },
    "demo": { en: p_demo_en, cn: p_demo_cn, tw: p_demo_tw, jp: p_demo_jp },
    "docs": { en: p_docs_en, cn: p_docs_cn, tw: p_docs_tw, jp: p_docs_jp },
    "docs/api": { en: p_docs_api_en, cn: p_docs_api_cn, tw: p_docs_api_tw, jp: p_docs_api_jp },
    "docs/sdk": { en: p_docs_sdk_en, cn: p_docs_sdk_cn, tw: p_docs_sdk_tw, jp: p_docs_sdk_jp },
    "pricing": { en: p_pricing_en, cn: p_pricing_cn, tw: p_pricing_tw, jp: p_pricing_jp },
    "privacy": { en: p_privacy_en, cn: p_privacy_cn, tw: p_privacy_tw, jp: p_privacy_jp },
    "security": { en: p_security_en, cn: p_security_cn, tw: p_security_tw, jp: p_security_jp },
    "terms": { en: p_terms_en, cn: p_terms_cn, tw: p_terms_tw, jp: p_terms_jp },
    "use-cases/rwa-tokenization": { en: p_use_cases_rwa_tokenization_en, cn: p_use_cases_rwa_tokenization_cn, tw: p_use_cases_rwa_tokenization_tw, jp: p_use_cases_rwa_tokenization_jp },
    "use-cases/smart-wallet": { en: p_use_cases_smart_wallet_en, cn: p_use_cases_smart_wallet_cn, tw: p_use_cases_smart_wallet_tw, jp: p_use_cases_smart_wallet_jp },
    "use-cases/stablecoin-compliance": { en: p_use_cases_stablecoin_compliance_en, cn: p_use_cases_stablecoin_compliance_cn, tw: p_use_cases_stablecoin_compliance_tw, jp: p_use_cases_stablecoin_compliance_jp },
};
