/* Auto-generated by scripts/html2jsx.py — page registry for the legacy catch-all routes. */
import type { ComponentType } from "react";
import type { Locale } from "./locales";

import p_about_en from "@/components/legacy/pages/about.en";
import p_about_cn from "@/components/legacy/pages/about.cn";
import p_about_tw from "@/components/legacy/pages/about.tw";
import p_about_jp from "@/components/legacy/pages/about.jp";
import p_address_check_en from "@/components/legacy/pages/address-check.en";
import p_address_check_cn from "@/components/legacy/pages/address-check.cn";
import p_address_check_tw from "@/components/legacy/pages/address-check.tw";
import p_address_check_jp from "@/components/legacy/pages/address-check.jp";
import p_blog_en from "@/components/legacy/pages/blog.en";
import p_blog_cn from "@/components/legacy/pages/blog.cn";
import p_blog_tw from "@/components/legacy/pages/blog.tw";
import p_blog_jp from "@/components/legacy/pages/blog.jp";
import p_blog_hong_kong_stablecoin_license_en from "@/components/legacy/pages/blog-hong-kong-stablecoin-license.en";
import p_blog_mica_stablecoin_compliance_en from "@/components/legacy/pages/blog-mica-stablecoin-compliance.en";
import p_blog_ofac_sanctions_screening_blockchain_en from "@/components/legacy/pages/blog-ofac-sanctions-screening-blockchain.en";
import p_blog_why_on_chain_compliance_en from "@/components/legacy/pages/blog-why-on-chain-compliance.en";
import p_blog_why_on_chain_compliance_cn from "@/components/legacy/pages/blog-why-on-chain-compliance.cn";
import p_blog_why_on_chain_compliance_tw from "@/components/legacy/pages/blog-why-on-chain-compliance.tw";
import p_blog_why_on_chain_compliance_jp from "@/components/legacy/pages/blog-why-on-chain-compliance.jp";
import p_case_studies_en from "@/components/legacy/pages/case-studies.en";
import p_changelog_en from "@/components/legacy/pages/changelog.en";
import p_changelog_cn from "@/components/legacy/pages/changelog.cn";
import p_changelog_tw from "@/components/legacy/pages/changelog.tw";
import p_changelog_jp from "@/components/legacy/pages/changelog.jp";
import p_contact_en from "@/components/legacy/pages/contact.en";
import p_demo_en from "@/components/legacy/pages/demo.en";
import p_demo_cn from "@/components/legacy/pages/demo.cn";
import p_demo_tw from "@/components/legacy/pages/demo.tw";
import p_demo_jp from "@/components/legacy/pages/demo.jp";
import p_docs_en from "@/components/legacy/pages/docs.en";
import p_docs_cn from "@/components/legacy/pages/docs.cn";
import p_docs_tw from "@/components/legacy/pages/docs.tw";
import p_docs_jp from "@/components/legacy/pages/docs.jp";
import p_docs_api_en from "@/components/legacy/pages/docs-api.en";
import p_docs_api_cn from "@/components/legacy/pages/docs-api.cn";
import p_docs_api_tw from "@/components/legacy/pages/docs-api.tw";
import p_docs_api_jp from "@/components/legacy/pages/docs-api.jp";
import p_docs_sdk_en from "@/components/legacy/pages/docs-sdk.en";
import p_docs_sdk_cn from "@/components/legacy/pages/docs-sdk.cn";
import p_docs_sdk_tw from "@/components/legacy/pages/docs-sdk.tw";
import p_docs_sdk_jp from "@/components/legacy/pages/docs-sdk.jp";
import p_pricing_en from "@/components/legacy/pages/pricing.en";
import p_pricing_cn from "@/components/legacy/pages/pricing.cn";
import p_pricing_tw from "@/components/legacy/pages/pricing.tw";
import p_pricing_jp from "@/components/legacy/pages/pricing.jp";
import p_privacy_en from "@/components/legacy/pages/privacy.en";
import p_privacy_cn from "@/components/legacy/pages/privacy.cn";
import p_privacy_tw from "@/components/legacy/pages/privacy.tw";
import p_privacy_jp from "@/components/legacy/pages/privacy.jp";
import p_security_en from "@/components/legacy/pages/security.en";
import p_security_cn from "@/components/legacy/pages/security.cn";
import p_security_tw from "@/components/legacy/pages/security.tw";
import p_security_jp from "@/components/legacy/pages/security.jp";
import p_terms_en from "@/components/legacy/pages/terms.en";
import p_terms_cn from "@/components/legacy/pages/terms.cn";
import p_terms_tw from "@/components/legacy/pages/terms.tw";
import p_terms_jp from "@/components/legacy/pages/terms.jp";
import p_use_cases_rwa_tokenization_en from "@/components/legacy/pages/use-cases-rwa-tokenization.en";
import p_use_cases_rwa_tokenization_cn from "@/components/legacy/pages/use-cases-rwa-tokenization.cn";
import p_use_cases_rwa_tokenization_tw from "@/components/legacy/pages/use-cases-rwa-tokenization.tw";
import p_use_cases_rwa_tokenization_jp from "@/components/legacy/pages/use-cases-rwa-tokenization.jp";
import p_use_cases_smart_wallet_en from "@/components/legacy/pages/use-cases-smart-wallet.en";
import p_use_cases_smart_wallet_cn from "@/components/legacy/pages/use-cases-smart-wallet.cn";
import p_use_cases_smart_wallet_tw from "@/components/legacy/pages/use-cases-smart-wallet.tw";
import p_use_cases_smart_wallet_jp from "@/components/legacy/pages/use-cases-smart-wallet.jp";
import p_use_cases_stablecoin_compliance_en from "@/components/legacy/pages/use-cases-stablecoin-compliance.en";
import p_use_cases_stablecoin_compliance_cn from "@/components/legacy/pages/use-cases-stablecoin-compliance.cn";
import p_use_cases_stablecoin_compliance_tw from "@/components/legacy/pages/use-cases-stablecoin-compliance.tw";
import p_use_cases_stablecoin_compliance_jp from "@/components/legacy/pages/use-cases-stablecoin-compliance.jp";

export type PageMeta = { title: string; description: string };
export type PageDef = {
  available: readonly Locale[];
  wallet: boolean;
  meta: Partial<Record<Locale, PageMeta>>;
};

export const pageDefs: Record<string, PageDef> = {
    "about": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "About — FidesOrigin | Programmable On-Chain Compliance", description: "FidesOrigin is building the infrastructure for programmable on-chain compliance. Meet the team behind the protocol." },
      cn: { title: "About — FidesOrigin | Programmable On-Chain Compliance", description: "FidesOrigin is building the infrastructure for programmable on-chain compliance. Meet the team behind the protocol." },
      tw: { title: "About — FidesOrigin | Programmable On-Chain Compliance", description: "FidesOrigin is building the infrastructure for programmable on-chain compliance. Meet the team behind the protocol." },
      jp: { title: "About — FidesOrigin | Programmable On-Chain Compliance", description: "FidesOrigin is building the infrastructure for programmable on-chain compliance. Meet the team behind the protocol." },
      },
    },
    "address-check": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: true,
      meta: {
      en: { title: "Address Risk Check | FidesOrigin", description: "Check Ethereum address risk in real-time. FidesOrigin scans 20,000+ risk addresses across OFAC, Chainalysis, and more." },
      cn: { title: "地址风险查询 | FidesOrigin", description: "实时查询以太坊地址风险。FidesOrigin扫描超过20,000个风险地址，涵盖OFAC、Chainalysis等来源。" },
      tw: { title: "地址風險查詢 | FidesOrigin", description: "即時查詢以太坊地址風險。FidesOrigin掃描超過20,000個風險地址，涵蓋OFAC、Chainalysis等來源。" },
      jp: { title: "住所リスクチェック | FidesOrigin", description: "イーサリアム住所のリスクをリアルタイムで確認。FidesOriginはOFAC、Chainalysisなど20,000件以上のリスク住所をスキャンします。" },
      },
    },
    "blog": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "FidesOrigin Blog — Insights on On-Chain Compliance", description: "Deep dives into programmable on-chain compliance, risk engines, and the future of DeFi regulation." },
      cn: { title: "FidesOrigin 博客 — 链上合规深度洞察", description: "风险引擎、DeFi 监管与确定性合规架构的深度解析。" },
      tw: { title: "FidesOrigin 博客 — 鏈上合規深度洞察", description: "風險引擎、DeFi 監管與確定性合規架構的深度解析。" },
      jp: { title: "FidesOrigin ブログ — オンチェーンコンプライアンスのインサイト", description: "リスクエンジン、DeFi 規制、決定論的コンプライアンスのアーキテクチャを深掘りします。" },
      },
    },
    "blog/hong-kong-stablecoin-license": {
      available: ["en"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Hong Kong Stablecoin License: Compliance Requirements — FidesOrigin Blog", description: "Guide to Hong Kong's stablecoin issuer licensing regime. HKMA requirements, reserve management, and on-chain compliance for VASPs." },
      },
    },
    "blog/mica-stablecoin-compliance": {
      available: ["en"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "MiCA Compliance for Stablecoins: A Technical Guide — FidesOrigin Blog", description: "Technical guide to EU MiCA compliance for stablecoin issuers. On-chain reserve attestations, transaction screening, and regulatory reporting requirements." },
      },
    },
    "blog/ofac-sanctions-screening-blockchain": {
      available: ["en"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "OFAC Sanctions Screening on Blockchain: Best Practices — FidesOrigin Blog", description: "Best practices for OFAC sanctions screening on blockchain. How to implement SDN list checks at the smart contract level for stablecoins and DeFi protocols." },
      },
    },
    "blog/why-on-chain-compliance": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Why On-Chain: The End of API-Based Compliance — FidesOrigin", description: "API-based compliance is an architectural mistake. The future is on-chain risk enforcement: deterministic, zero-latency, and impossible to bypass." },
      cn: { title: "为何链上：API 合规模式的终结 — FidesOrigin", description: "基于 API 的合规是一种架构层面的错误。未来属于链上风险执行：确定性、零延迟、无法绕过的原生执行。" },
      tw: { title: "為何鏈上：API 合規模式的終結 — FidesOrigin", description: "基於 API 的合規是一種架構層面的錯誤。未來屬於鏈上風險執行：確定性、零延遲、無法繞過的原生執行。" },
      jp: { title: "なぜオンチェーンか：API ベースコンプライアンスの終焉 — FidesOrigin", description: "API ベースのコンプライアンスはアーキテクチャ的な誤りだ。未来はオンチェーンリスクエンフォースメント：決定論的、ゼロレイテンシー、迂回不可能。" },
      },
    },
    "case-studies": {
      available: ["en"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Case Studies — FidesOrigin | On-Chain Compliance in Production", description: "See how leading stablecoin issuers, RWA platforms, and DeFi protocols use FidesOrigin for deterministic on-chain compliance." },
      },
    },
    "changelog": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Changelog — FidesOrigin | Protocol Updates", description: "Track FidesOrigin protocol updates, security audits, and feature releases. From v1.0 to the latest." },
      cn: { title: "Changelog — FidesOrigin | Protocol Updates", description: "Track FidesOrigin protocol updates, security audits, and feature releases. From v1.0 to the latest." },
      tw: { title: "Changelog — FidesOrigin | Protocol Updates", description: "Track FidesOrigin protocol updates, security audits, and feature releases. From v1.0 to the latest." },
      jp: { title: "Changelog — FidesOrigin | Protocol Updates", description: "Track FidesOrigin protocol updates, security audits, and feature releases. From v1.0 to the latest." },
      },
    },
    "contact": {
      available: ["en"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Contact — FidesOrigin | Get Started with On-Chain Compliance", description: "Get in touch with the FidesOrigin team. Request a demo, discuss your compliance needs, or explore partnership opportunities." },
      },
    },
    "demo": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Interactive Demo — FidesOrigin | On-Chain Compliance Engine", description: "Try FidesOrigin's on-chain compliance engine live on Sepolia testnet. Screen addresses, check risk scores, and see quarantine in action." },
      cn: { title: "Interactive Demo — FidesOrigin | On-Chain Compliance Engine", description: "Try FidesOrigin's on-chain compliance engine live on Sepolia testnet. Screen addresses, check risk scores, and see quarantine in action." },
      tw: { title: "Interactive Demo — FidesOrigin | On-Chain Compliance Engine", description: "Try FidesOrigin's on-chain compliance engine live on Sepolia testnet. Screen addresses, check risk scores, and see quarantine in action." },
      jp: { title: "Interactive Demo — FidesOrigin | On-Chain Compliance Engine", description: "Try FidesOrigin's on-chain compliance engine live on Sepolia testnet. Screen addresses, check risk scores, and see quarantine in action." },
      },
    },
    "docs": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Documentation — FidesOrigin", description: "FidesOrigin V2.1 documentation. Quick start, core concepts, Guard integration, architecture overview." },
      cn: { title: "文档 — FidesOrigin", description: "FidesOrigin 文档。快速开始、核心概念、架构概览。" },
      tw: { title: "文件 — FidesOrigin", description: "FidesOrigin 文件。快速開始、核心概念、架構概覽。" },
      jp: { title: "ドキュメント — FidesOrigin", description: "FidesOrigin ドキュメント。クイックスタート、核心概念、アーキテクチャ概要。" },
      },
    },
    "docs/api": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "API Reference — FidesOrigin", description: "FidesOrigin V2.1 REST API reference. Endpoints for address risk checks, rules, batch screening, and monitoring." },
      cn: { title: "API 参考 — FidesOrigin", description: "FidesOrigin REST API 参考。地址风险检查、规则管理和风险评估的端点。" },
      tw: { title: "API 參考 — FidesOrigin", description: "FidesOrigin REST API 參考。地址風險檢查、規則管理和風險評估的端點。" },
      jp: { title: "API リファレンス — FidesOrigin", description: "FidesOrigin REST API リファレンス。住所リスクチェック、ルール管理、リスク評価のエンドポイント。" },
      },
    },
    "docs/sdk": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK V2.1. Install, configure, and integrate on-chain compliance with Guard support." },
      cn: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK。安装、配置并集成链上合规。" },
      tw: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK。安裝、配置並集成鏈上合規。" },
      jp: { title: "SDK — FidesOrigin", description: "FidesOrigin JavaScript SDK。インストール、設定、オンチェーン・コンプライアンスの統合。" },
      },
    },
    "pricing": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Pricing — FidesOrigin | On-Chain Compliance Infrastructure", description: "Transparent pricing for on-chain compliance infrastructure. Start free, scale as you grow. Built for stablecoin issuers, RWA platforms, and DeFi protocols." },
      cn: { title: "定价 — FidesOrigin | 链上合规基础设施", description: "链上合规基础设施的透明定价。免费开始，随业务增长而扩展。为稳定币发行方、RWA平台和DeFi协议打造。" },
      tw: { title: "Pricing — FidesOrigin | On-Chain Compliance Infrastructure", description: "Transparent pricing for on-chain compliance infrastructure. Start free, scale as you grow. Built for stablecoin issuers, RWA platforms, and DeFi protocols." },
      jp: { title: "Pricing — FidesOrigin | On-Chain Compliance Infrastructure", description: "Transparent pricing for on-chain compliance infrastructure. Start free, scale as you grow. Built for stablecoin issuers, RWA platforms, and DeFi protocols." },
      },
    },
    "privacy": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Privacy Policy — FidesOrigin", description: "FidesOrigin privacy policy. How we handle data, cookies, and user information." },
      cn: { title: "隐私政策 — FidesOrigin", description: "FidesOrigin 隐私政策。我们如何处理数据、Cookie 和用户信息。" },
      tw: { title: "隱私政策 — FidesOrigin", description: "FidesOrigin 隱私政策。我們如何處理數據、Cookie 和用戶信息。" },
      jp: { title: "プライバシーポリシー — FidesOrigin", description: "FidesOrigin プライバシーポリシー。データ、Cookie、ユーザー情報の取り扱いについて。" },
      },
    },
    "security": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Security & Audits — FidesOrigin | Triple-Audited On-Chain Compliance", description: "FidesOrigin has completed 3 rounds of comprehensive security audits, covering 300+ findings. View our audit reports and security posture." },
      cn: { title: "Security & Audits — FidesOrigin | Triple-Audited On-Chain Compliance", description: "FidesOrigin has completed 3 rounds of comprehensive security audits, covering 300+ findings. View our audit reports and security posture." },
      tw: { title: "Security & Audits — FidesOrigin | Triple-Audited On-Chain Compliance", description: "FidesOrigin has completed 3 rounds of comprehensive security audits, covering 300+ findings. View our audit reports and security posture." },
      jp: { title: "Security & Audits — FidesOrigin | Triple-Audited On-Chain Compliance", description: "FidesOrigin has completed 3 rounds of comprehensive security audits, covering 300+ findings. View our audit reports and security posture." },
      },
    },
    "terms": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Terms of Service — FidesOrigin", description: "FidesOrigin terms of service. Rules and conditions for using our platform." },
      cn: { title: "服务条款 — FidesOrigin", description: "FidesOrigin 服务条款。使用我们平台的规则和条件。" },
      tw: { title: "服務條款 — FidesOrigin", description: "FidesOrigin 服務條款。使用我們平台的規則和條件。" },
      jp: { title: "利用規約 — FidesOrigin", description: "FidesOrigin 利用規約。プラットフォームの使用ルールと条件。" },
      },
    },
    "use-cases/rwa-tokenization": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "RWA Tokenization Compliance — FidesOrigin", description: "Compliant RWA tokenization with on-chain securities enforcement. Accredited investor verification, jurisdiction checks, and on-chain KYC for tokenized real world assets." },
      cn: { title: "RWA Tokenization Compliance — FidesOrigin", description: "Compliant RWA tokenization with on-chain securities enforcement. Accredited investor verification, jurisdiction checks, and on-chain KYC for tokenized real world assets." },
      tw: { title: "RWA Tokenization Compliance — FidesOrigin", description: "Compliant RWA tokenization with on-chain securities enforcement. Accredited investor verification, jurisdiction checks, and on-chain KYC for tokenized real world assets." },
      jp: { title: "RWA Tokenization Compliance — FidesOrigin", description: "Compliant RWA tokenization with on-chain securities enforcement. Accredited investor verification, jurisdiction checks, and on-chain KYC for tokenized real world assets." },
      },
    },
    "use-cases/smart-wallet": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Smart Wallet Compliance — FidesOrigin | Account Abstraction Risk Screening", description: "Embed on-chain risk screening into smart wallets and account abstraction wallets. Screen every userOp before execution with FidesOrigin." },
      cn: { title: "Smart Wallet Compliance — FidesOrigin | Account Abstraction Risk Screening", description: "Embed on-chain risk screening into smart wallets and account abstraction wallets. Screen every userOp before execution with FidesOrigin." },
      tw: { title: "Smart Wallet Compliance — FidesOrigin | Account Abstraction Risk Screening", description: "Embed on-chain risk screening into smart wallets and account abstraction wallets. Screen every userOp before execution with FidesOrigin." },
      jp: { title: "Smart Wallet Compliance — FidesOrigin | Account Abstraction Risk Screening", description: "Embed on-chain risk screening into smart wallets and account abstraction wallets. Screen every userOp before execution with FidesOrigin." },
      },
    },
    "use-cases/stablecoin-compliance": {
      available: ["en", "cn", "tw", "jp"] as unknown as readonly Locale[],
      wallet: false,
      meta: {
      en: { title: "Stablecoin Compliance Solution — FidesOrigin", description: "Build compliant stablecoins with on-chain risk screening. Meet MiCA, Hong Kong, and global regulations with deterministic compliance enforcement." },
      cn: { title: "Stablecoin Compliance Solution — FidesOrigin", description: "Build compliant stablecoins with on-chain risk screening. Meet MiCA, Hong Kong, and global regulations with deterministic compliance enforcement." },
      tw: { title: "Stablecoin Compliance Solution — FidesOrigin", description: "Build compliant stablecoins with on-chain risk screening. Meet MiCA, Hong Kong, and global regulations with deterministic compliance enforcement." },
      jp: { title: "Stablecoin Compliance Solution — FidesOrigin", description: "Build compliant stablecoins with on-chain risk screening. Meet MiCA, Hong Kong, and global regulations with deterministic compliance enforcement." },
      },
    },
};

export const pageContent: Record<string, Partial<Record<Locale, ComponentType>>> = {
    "about": { en: p_about_en, cn: p_about_cn, tw: p_about_tw, jp: p_about_jp },
    "address-check": { en: p_address_check_en, cn: p_address_check_cn, tw: p_address_check_tw, jp: p_address_check_jp },
    "blog": { en: p_blog_en, cn: p_blog_cn, tw: p_blog_tw, jp: p_blog_jp },
    "blog/hong-kong-stablecoin-license": { en: p_blog_hong_kong_stablecoin_license_en },
    "blog/mica-stablecoin-compliance": { en: p_blog_mica_stablecoin_compliance_en },
    "blog/ofac-sanctions-screening-blockchain": { en: p_blog_ofac_sanctions_screening_blockchain_en },
    "blog/why-on-chain-compliance": { en: p_blog_why_on_chain_compliance_en, cn: p_blog_why_on_chain_compliance_cn, tw: p_blog_why_on_chain_compliance_tw, jp: p_blog_why_on_chain_compliance_jp },
    "case-studies": { en: p_case_studies_en },
    "changelog": { en: p_changelog_en, cn: p_changelog_cn, tw: p_changelog_tw, jp: p_changelog_jp },
    "contact": { en: p_contact_en },
    "demo": { en: p_demo_en, cn: p_demo_cn, tw: p_demo_tw, jp: p_demo_jp },
    "docs": { en: p_docs_en, cn: p_docs_cn, tw: p_docs_tw, jp: p_docs_jp },
    "docs/api": { en: p_docs_api_en, cn: p_docs_api_cn, tw: p_docs_api_tw, jp: p_docs_api_jp },
    "docs/sdk": { en: p_docs_sdk_en, cn: p_docs_sdk_cn, tw: p_docs_sdk_tw, jp: p_docs_sdk_jp },
    "pricing": { en: p_pricing_en, cn: p_pricing_cn, tw: p_pricing_tw, jp: p_pricing_jp },
    "privacy": { en: p_privacy_en, cn: p_privacy_cn, tw: p_privacy_tw, jp: p_privacy_jp },
    "security": { en: p_security_en, cn: p_security_cn, tw: p_security_tw, jp: p_security_jp },
    "terms": { en: p_terms_en, cn: p_terms_cn, tw: p_terms_tw, jp: p_terms_jp },
    "use-cases/rwa-tokenization": { en: p_use_cases_rwa_tokenization_en, cn: p_use_cases_rwa_tokenization_cn, tw: p_use_cases_rwa_tokenization_tw, jp: p_use_cases_rwa_tokenization_jp },
    "use-cases/smart-wallet": { en: p_use_cases_smart_wallet_en, cn: p_use_cases_smart_wallet_cn, tw: p_use_cases_smart_wallet_tw, jp: p_use_cases_smart_wallet_jp },
    "use-cases/stablecoin-compliance": { en: p_use_cases_stablecoin_compliance_en, cn: p_use_cases_stablecoin_compliance_cn, tw: p_use_cases_stablecoin_compliance_tw, jp: p_use_cases_stablecoin_compliance_jp },
};
