"""Initial migration - Create all tables

Revision ID: 001
Revises: 
Create Date: 2024-04-03 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 risk_level 枚举类型
    risk_level_enum = sa.Enum('low', 'medium', 'high', 'critical', name='risklevel')
    risk_level_enum.create(op.get_bind())
    
    # 创建 risk_status 枚举类型
    risk_status_enum = sa.Enum('pending', 'confirmed', 'false_positive', 'whitelisted', name='riskstatus')
    risk_status_enum.create(op.get_bind())
    
    # 创建 address_risks 表
    # [MEDIUM Fix #16] id 类型改为 BigInteger 以匹配 models.py
    op.create_table('address_risks',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('address', sa.String(255), nullable=False),
        sa.Column('chain', sa.String(50), nullable=False, server_default='ethereum'),
        sa.Column('risk_score', sa.Numeric(5, 2), nullable=False, server_default='0.0'),
        sa.Column('risk_level', sa.String(20), nullable=False, server_default='LOW'),
        sa.Column('risk_factors', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(50), nullable=False, server_default='PENDING'),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('report_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('address', 'chain', name='uix_address_risk_address_chain')
    )
    
    # 创建索引
    op.create_index('ix_address_risks_address', 'address_risks', ['address'])
    op.create_index('ix_address_risks_chain_address', 'address_risks', ['chain', 'address'], unique=True)
    op.create_index('ix_address_risks_risk_level', 'address_risks', ['risk_level'])
    op.create_index('ix_address_risks_status', 'address_risks', ['status'])
    
    # 创建 transactions 表
    # [MEDIUM Fix #16] id 类型改为 BigInteger，字段名对齐 models.py
    op.create_table('transactions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('tx_hash', sa.String(255), nullable=False),
        sa.Column('chain', sa.String(50), nullable=False, server_default='ethereum'),
        sa.Column('from_address', sa.String(255), nullable=False),
        sa.Column('to_address', sa.String(255), nullable=False),
        sa.Column('from_address_id', sa.BigInteger(), nullable=True),
        sa.Column('to_address_id', sa.BigInteger(), nullable=True),
        sa.Column('address', sa.String(255), nullable=True),
        sa.Column('value', sa.Numeric(36, 18), nullable=False),
        sa.Column('value_usd', sa.Numeric(24, 8), nullable=True),
        sa.Column('token_symbol', sa.String(50), nullable=True),
        sa.Column('token_address', sa.String(255), nullable=True),
        sa.Column('block_number', sa.BigInteger(), nullable=False),
        sa.Column('block_hash', sa.String(255), nullable=True),
        sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('risk_score', sa.Numeric(5, 2), nullable=False, server_default='0.0'),
        sa.Column('risk_level', risk_level_enum, nullable=False, server_default='UNKNOWN'),
        sa.Column('risk_factors', sa.JSON(), nullable=True),
        sa.Column('risk_indicators', sa.JSON(), nullable=True),
        sa.Column('gas_used', sa.BigInteger(), nullable=True),
        sa.Column('gas_price', sa.Numeric(36, 18), nullable=True),
        sa.Column('tx_fee_usd', sa.Numeric(24, 8), nullable=True),
        sa.Column('status', sa.String(50), nullable=False, server_default='confirmed'),
        sa.Column('is_suspicious', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tx_hash', 'chain', name='uix_tx_hash_chain')
    )
    
    # 创建索引
    op.create_index('ix_transactions_tx_hash', 'transactions', ['tx_hash'])
    op.create_index('ix_transactions_address', 'transactions', ['address'])
    op.create_index('ix_transactions_chain_block', 'transactions', ['chain', 'block_number'])
    op.create_index('ix_transactions_from_address', 'transactions', ['from_address'])
    op.create_index('ix_transactions_to_address', 'transactions', ['to_address'])
    op.create_index('ix_transactions_block_timestamp', 'transactions', ['block_timestamp'])
    
    # 创建 risk_rules 表
    # [MEDIUM Fix #16] id 类型改为 BigInteger
    op.create_table('risk_rules',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(255), nullable=False, unique=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('rule_type', sa.String(50), nullable=False),
        sa.Column('category', sa.String(100), nullable=True),
        sa.Column('pattern', sa.String(500), nullable=True),
        sa.Column('threshold_value', sa.Numeric(24, 8), nullable=True),
        sa.Column('risk_score_increment', sa.Numeric(5, 2), server_default='0', nullable=True),
        sa.Column('condition', sa.JSON(), nullable=True),
        sa.Column('risk_weight', sa.Numeric(5, 2), server_default='1.0', nullable=True),
        sa.Column('risk_score_impact', sa.Numeric(5, 2), server_default='0.0', nullable=True),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('priority', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('created_by', sa.String(255), server_default='system', nullable=True),
        sa.Column('updated_by', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建索引
    op.create_index('ix_risk_rules_name', 'risk_rules', ['name'])
    op.create_index('ix_risk_rules_type', 'risk_rules', ['rule_type'])
    op.create_index('ix_risk_rules_category', 'risk_rules', ['category'])
    op.create_index('ix_risk_rules_active', 'risk_rules', ['is_active'])
    
    # 创建 risk_events 表
    # [MEDIUM Fix #16] id 类型改为 BigInteger
    op.create_table('risk_events',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('event_type', sa.String(100), nullable=False),
        sa.Column('severity', risk_level_enum, nullable=False, server_default='UNKNOWN'),
        sa.Column('address', sa.String(255), nullable=False),
        sa.Column('address_id', sa.BigInteger(), nullable=True),
        sa.Column('tx_hash', sa.String(255), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('triggered_rules', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('status', sa.String(50), server_default='PENDING', nullable=True),
        sa.Column('is_notified', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('assigned_to', sa.String(255), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolution_notes', sa.Text(), nullable=True),
        sa.Column('event_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建索引
    op.create_index('ix_risk_events_event_type', 'risk_events', ['event_type'])
    op.create_index('ix_risk_events_address', 'risk_events', ['address'])
    op.create_index('ix_risk_events_tx_hash', 'risk_events', ['tx_hash'])
    op.create_index('ix_risk_events_severity', 'risk_events', ['severity'])
    op.create_index('ix_risk_events_created_at', 'risk_events', ['created_at'])
    op.create_index('ix_risk_events_notified', 'risk_events', ['is_notified'])
    
    # 创建 address_reports 表
    op.create_table('address_reports',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('address', sa.String(255), nullable=False),
        sa.Column('chain', sa.String(50), nullable=False, server_default='ethereum'),
        sa.Column('report_type', sa.String(100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('evidence', sa.JSON(), nullable=True),
        sa.Column('reporter_email', sa.String(255), nullable=True),
        sa.Column('reporter_wallet', sa.String(255), nullable=True),
        sa.Column('status', sa.String(50), server_default='pending', nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建索引
    op.create_index('ix_address_reports_address', 'address_reports', ['address'])
    op.create_index('ix_address_reports_status', 'address_reports', ['status'])
    op.create_index('ix_address_reports_type', 'address_reports', ['report_type'])
    op.create_index('ix_address_reports_reporter', 'address_reports', ['reporter_wallet'])
    
    # 创建 system_configs 表
    op.create_table('system_configs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('key', sa.String(100), nullable=False, unique=True),
        sa.Column('value', sa.JSON(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('ix_system_configs_key', 'system_configs', ['key'])
    
    # 插入默认风险规则
    # [MEDIUM Fix #16] 使用 autoincrement BigInteger id 而非 UUID
    op.execute("""
        INSERT INTO risk_rules (name, description, rule_type, category, condition, risk_weight, risk_score_impact, priority, tags, is_active, created_at, updated_at)
        VALUES
        ('reported_address', '地址被多次举报', 'PATTERN', 'reputation', '{"min_reports": 1, "weight": 0.3}'::json, 0.3, 50.0, 10, ARRAY['reputation', 'report']::text[], true, now(), now()),
        ('high_frequency_transactions', '高频交易模式', 'PATTERN', 'behavior', '{"max_transactions_per_hour": 10, "weight": 0.2}'::json, 0.2, 40.0, 20, ARRAY['behavior', 'frequency']::text[], true, now(), now()),
        ('large_amount_transfer', '大额转账', 'PATTERN', 'amount', '{"threshold_eth": 100, "weight": 0.15}'::json, 0.15, 30.0, 30, ARRAY['amount', 'transfer']::text[], true, now(), now()),
        ('new_address', '新创建地址', 'PATTERN', 'age', '{"min_days": 7, "weight": 0.1}'::json, 0.1, 20.0, 40, ARRAY['age', 'new']::text[], true, now(), now()),
        ('contract_interaction', '可疑合约交互', 'PATTERN', 'contract', '{"suspicious_opcodes": ["SELFDESTRUCT", "DELEGATECALL"], "weight": 0.25}'::json, 0.25, 45.0, 15, ARRAY['contract', 'opcode']::text[], true, now(), now())
        ON CONFLICT (name) DO NOTHING
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除表（按依赖顺序）
    op.drop_table('system_configs')
    op.drop_table('address_reports')
    op.drop_table('risk_events')
    op.drop_table('risk_rules')
    op.drop_table('transactions')
    op.drop_table('address_risks')
    
    # 删除枚举类型
    risk_level_enum = sa.Enum('low', 'medium', 'high', 'critical', name='risklevel')
    risk_status_enum = sa.Enum('pending', 'confirmed', 'false_positive', 'whitelisted', name='riskstatus')
    
    risk_level_enum.drop(op.get_bind())
    risk_status_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###
