"""Initial migration - Create all tables

Revision ID: 001
Revises: 
Create Date: 2024-04-03 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 risk_level 枚举类型
    risk_level_enum = sa.Enum('low', 'medium', 'high', 'critical', name='risklevel')
    risk_level_enum.create(op.get_bind())
    
    # 创建 risk_status 枚举类型
    risk_status_enum = sa.Enum('pending', 'confirmed', 'false_positive', 'whitelisted', name='riskstatus')
    risk_status_enum.create(op.get_bind())
    
    # 创建 address_risks 表
    op.create_table('address_risks',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('address', sa.String(42), nullable=False),
        sa.Column('chain', sa.String(20), nullable=False, server_default='ethereum'),
        sa.Column('risk_score', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('risk_level', risk_level_enum, nullable=False, server_default='low'),
        sa.Column('risk_factors', sa.JSON(), nullable=True),
        sa.Column('status', risk_status_enum, nullable=False, server_default='pending'),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('report_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('address')
    )
    
    # 创建索引
    op.create_index('ix_address_risks_address', 'address_risks', ['address'])
    op.create_index('ix_address_risks_chain_address', 'address_risks', ['chain', 'address'], unique=True)
    op.create_index('ix_address_risks_risk_level', 'address_risks', ['risk_level'])
    op.create_index('ix_address_risks_status', 'address_risks', ['status'])
    
    # 创建 transactions 表
    op.create_table('transactions',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tx_hash', sa.String(66), nullable=False),
        sa.Column('chain', sa.String(20), nullable=False, server_default='ethereum'),
        sa.Column('address', sa.String(42), nullable=False),
        sa.Column('from_address', sa.String(42), nullable=False),
        sa.Column('to_address', sa.String(42), nullable=False),
        sa.Column('value', sa.String(50), nullable=False),
        sa.Column('gas_price', sa.String(50), nullable=True),
        sa.Column('gas_used', sa.BigInteger(), nullable=True),
        sa.Column('block_number', sa.BigInteger(), nullable=False),
        sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
        sa.Column('risk_score', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('risk_level', risk_level_enum, nullable=False, server_default='low'),
        sa.Column('risk_indicators', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('raw_data', sa.JSON(), nullable=True),
        sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tx_hash'),
        sa.ForeignKeyConstraint(['address'], ['address_risks.address'])
    )
    
    # 创建索引
    op.create_index('ix_transactions_tx_hash', 'transactions', ['tx_hash'])
    op.create_index('ix_transactions_address', 'transactions', ['address'])
    op.create_index('ix_transactions_chain_block', 'transactions', ['chain', 'block_number'])
    op.create_index('ix_transactions_from_address', 'transactions', ['from_address'])
    op.create_index('ix_transactions_to_address', 'transactions', ['to_address'])
    op.create_index('ix_transactions_block_timestamp', 'transactions', ['block_timestamp'])
    
    # 创建 risk_rules 表
    op.create_table('risk_rules',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(100), nullable=False, unique=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('rule_type', sa.String(50), nullable=False),
        sa.Column('category', sa.String(50), nullable=False),
        sa.Column('condition', sa.JSON(), nullable=False),
        sa.Column('risk_weight', sa.Float(), nullable=False, server_default='1.0'),
        sa.Column('risk_score_impact', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('priority', sa.Integer(), nullable=False, server_default='100'),
        sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('created_by', sa.String(100), nullable=True),
        sa.Column('updated_by', sa.String(100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # 创建索引
    op.create_index('ix_risk_rules_name', 'risk_rules', ['name'])
    op.create_index('ix_risk_rules_type', 'risk_rules', ['rule_type'])
    op.create_index('ix_risk_rules_category', 'risk_rules', ['category'])
    op.create_index('ix_risk_rules_active', 'risk_rules', ['is_active'])
    
    # 创建 risk_events 表
    op.create_table('risk_events',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('event_type', sa.String(50), nullable=False),
        sa.Column('severity', risk_level_enum, nullable=False),
        sa.Column('address', sa.String(42), nullable=False),
        sa.Column('tx_hash', sa.String(66), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('triggered_rules', postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column('is_notified', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['address'], ['address_risks.address'])
    )
    
    # 创建索引
    op.create_index('ix_risk_events_event_type', 'risk_events', ['event_type'])
    op.create_index('ix_risk_events_address', 'risk_events', ['address'])
    op.create_index('ix_risk_events_tx_hash', 'risk_events', ['tx_hash'])
    op.create_index('ix_risk_events_severity', 'risk_events', ['severity'])
    op.create_index('ix_risk_events_created_at', 'risk_events', ['created_at'])
    op.create_index('ix_risk_events_notified', 'risk_events', ['is_notified'])
    
    # 创建 address_reports 表
    op.create_table('address_reports',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('address', sa.String(42), nullable=False),
        sa.Column('chain', sa.String(20), nullable=False, server_default='ethereum'),
        sa.Column('report_type', sa.String(50), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('evidence', sa.JSON(), nullable=True),
        sa.Column('reporter_email', sa.String(100), nullable=True),
        sa.Column('reporter_wallet', sa.String(42), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('reviewed_by', sa.String(100), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['address'], ['address_risks.address'])
    )
    
    # 创建索引
    op.create_index('ix_address_reports_address', 'address_reports', ['address'])
    op.create_index('ix_address_reports_status', 'address_reports', ['status'])
    op.create_index('ix_address_reports_type', 'address_reports', ['report_type'])
    op.create_index('ix_address_reports_reporter', 'address_reports', ['reporter_wallet'])
    
    # 创建 system_configs 表
    op.create_table('system_configs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('key', sa.String(100), nullable=False, unique=True),
        sa.Column('value', sa.JSON(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_by', sa.String(100), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index('ix_system_configs_key', 'system_configs', ['key'])
    
    # 插入默认风险规则
    op.bulk_insert('risk_rules', [
        {
            'id': str(uuid.uuid4()),
            'name': 'reported_address',
            'description': '地址被多次举报',
            'rule_type': 'reputation',
            'category': 'reputation',
            'condition': {'min_reports': 1, 'weight': 0.3},
            'risk_weight': 0.3,
            'risk_score_impact': 50.0,
            'priority': 10,
            'tags': ['reputation', 'report']
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'high_frequency_transactions',
            'description': '高频交易模式',
            'rule_type': 'behavior',
            'category': 'behavior',
            'condition': {'max_transactions_per_hour': 10, 'weight': 0.2},
            'risk_weight': 0.2,
            'risk_score_impact': 40.0,
            'priority': 20,
            'tags': ['behavior', 'frequency']
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'large_amount_transfer',
            'description': '大额转账',
            'rule_type': 'amount',
            'category': 'amount',
            'condition': {'threshold_eth': 100, 'weight': 0.15},
            'risk_weight': 0.15,
            'risk_score_impact': 30.0,
            'priority': 30,
            'tags': ['amount', 'transfer']
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'new_address',
            'description': '新创建地址',
            'rule_type': 'age',
            'category': 'age',
            'condition': {'min_days': 7, 'weight': 0.1},
            'risk_weight': 0.1,
            'risk_score_impact': 20.0,
            'priority': 40,
            'tags': ['age', 'new']
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'contract_interaction',
            'description': '可疑合约交互',
            'rule_type': 'contract',
            'category': 'contract',
            'condition': {'suspicious_opcodes': ['SELFDESTRUCT', 'DELEGATECALL'], 'weight': 0.25},
            'risk_weight': 0.25,
            'risk_score_impact': 45.0,
            'priority': 15,
            'tags': ['contract', 'opcode']
        }
    ])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除表（按依赖顺序）
    op.drop_table('system_configs')
    op.drop_table('address_reports')
    op.drop_table('risk_events')
    op.drop_table('risk_rules')
    op.drop_table('transactions')
    op.drop_table('address_risks')
    
    # 删除枚举类型
    risk_level_enum = sa.Enum('low', 'medium', 'high', 'critical', name='risklevel')
    risk_status_enum = sa.Enum('pending', 'confirmed', 'false_positive', 'whitelisted', name='riskstatus')
    
    risk_level_enum.drop(op.get_bind())
    risk_status_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###
