global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fidesorigin-publisher'
    static_configs:
      - targets: ['data-publisher:9090']
    metrics_path: '/metrics'
